# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-for-data-science',
                'doc_host': 'https://ujjwal rastogi.github.io',
                'git_url': 'https://github.com/ujjwal rastogi/python-for-data-science',
                'lib_path': 'python_for_data_science'},
  'syms': {'python_for_data_science.core': {'python_for_data_science.core.foo': ('core.html#foo', 'python_for_data_science/core.py')}}}
